/**
 * Keyword dictionaries used to turn a plain-English query into search terms
 * and scoring weights. No LLM involved — a category is picked when the query
 * contains one of its trigger words, and its terms then drive both the Gmail
 * search and the relevance score.
 *
 * Weights are rough "how strongly does this phrase indicate the category"
 * points. Multi-word terms are treated as phrases and score higher when they
 * appear verbatim.
 */

export const CATEGORIES = [
  {
    id: 'job_offer',
    triggers: [
      'job',
      'jobs',
      'offer',
      'offers',
      'career',
      'careers',
      'hiring',
      'recruiter',
      'recruiting',
      'interview',
      'interviews',
      'position',
      'employment',
      'application',
      'applications',
    ],
    terms: [
      ['pleased to offer', 45],
      ['offer letter', 42],
      ['job offer', 40],
      ['offer of employment', 40],
      ['we would like to offer', 38],
      ['excited to offer', 36],
      ['your application', 26],
      ['interview', 24],
      ['recruiter', 20],
      ['hiring manager', 20],
      ['job opportunity', 20],
      ['compensation', 18],
      ['start date', 16],
      ['onboarding', 14],
      ['salary', 16],
      ['position', 12],
      ['role', 8],
    ],
  },
  {
    id: 'wedding',
    triggers: ['wedding', 'weddings', 'marriage', 'bride', 'groom', 'nuptials'],
    terms: [
      ['save the date', 38],
      ['wedding invitation', 38],
      ['are getting married', 36],
      ['wedding', 30],
      ['ceremony', 22],
      ['reception', 20],
      ['rsvp', 24],
      ['bridal', 22],
      ['registry', 16],
      ['engagement', 16],
      ['bridesmaid', 18],
      ['groomsmen', 18],
    ],
  },
  {
    id: 'invite',
    triggers: [
      'invite',
      'invites',
      'invitation',
      'invitations',
      'invited',
      'party',
      'parties',
      'event',
      'events',
      'rsvp',
      'birthday',
      'celebration',
    ],
    terms: [
      ['you are invited', 38],
      ["you're invited", 38],
      ['save the date', 32],
      ['invitation', 30],
      ['rsvp', 28],
      ['join us', 24],
      ['birthday', 22],
      ['celebration', 18],
      ['party', 18],
      ['hosted by', 14],
      ['guest list', 14],
    ],
  },
  {
    id: 'travel',
    triggers: [
      'flight',
      'flights',
      'travel',
      'trip',
      'trips',
      'hotel',
      'hotels',
      'booking',
      'bookings',
      'itinerary',
      'vacation',
      'airbnb',
      'airline',
      'boarding',
    ],
    terms: [
      ['booking confirmation', 38],
      ['flight confirmation', 38],
      ['your itinerary', 34],
      ['boarding pass', 34],
      ['check-in', 22],
      ['reservation', 26],
      ['confirmation number', 24],
      ['departure', 20],
      ['hotel', 20],
      ['flight', 24],
      ['itinerary', 26],
      ['baggage', 14],
    ],
  },
  {
    id: 'receipt',
    triggers: [
      'receipt',
      'receipts',
      'purchase',
      'purchases',
      'order',
      'orders',
      'bought',
      'payment',
      'payments',
      'charged',
      'invoice',
      'invoices',
      'spent',
    ],
    terms: [
      ['your receipt', 38],
      ['order confirmation', 36],
      ['payment received', 32],
      ['thank you for your order', 32],
      ['receipt', 28],
      ['invoice', 28],
      ['order number', 24],
      ['total charged', 24],
      ['transaction', 20],
      ['purchase', 20],
      ['refund', 18],
    ],
  },
  {
    id: 'bill',
    triggers: [
      'bill',
      'bills',
      'due',
      'subscription',
      'subscriptions',
      'renewal',
      'renew',
      'statement',
      'statements',
      'billing',
    ],
    terms: [
      ['payment due', 38],
      ['your statement', 34],
      ['auto-renew', 30],
      ['subscription renewal', 32],
      ['amount due', 32],
      ['past due', 30],
      ['billing', 24],
      ['statement', 22],
      ['due date', 24],
      ['autopay', 18],
    ],
  },
  {
    id: 'shipping',
    triggers: [
      'package',
      'packages',
      'delivery',
      'deliveries',
      'shipped',
      'shipping',
      'tracking',
      'parcel',
      'courier',
    ],
    terms: [
      ['has shipped', 38],
      ['out for delivery', 38],
      ['tracking number', 36],
      ['your package', 32],
      ['delivered', 26],
      ['shipment', 24],
      ['shipping', 22],
      ['arriving', 20],
      ['courier', 16],
    ],
  },
  {
    id: 'appointment',
    triggers: [
      'appointment',
      'appointments',
      'meeting',
      'meetings',
      'schedule',
      'scheduled',
      'booking',
      'reminder',
      'doctor',
      'dentist',
      'call',
    ],
    terms: [
      ['appointment confirmed', 38],
      ['appointment reminder', 36],
      ['your appointment', 34],
      ['scheduled for', 26],
      ['meeting invitation', 28],
      ['calendar invite', 28],
      ['appointment', 26],
      ['reschedule', 20],
      ['confirm your', 16],
    ],
  },
  {
    id: 'finance',
    triggers: [
      'tax',
      'taxes',
      'bank',
      'banking',
      'investment',
      'investments',
      'refund',
      'refunds',
      'insurance',
      'loan',
      'loans',
      'mortgage',
    ],
    terms: [
      ['tax document', 38],
      ['tax return', 36],
      ['account statement', 32],
      ['w-2', 34],
      ['1099', 34],
      ['tax refund', 34],
      ['insurance', 24],
      ['policy', 18],
      ['loan', 22],
      ['interest rate', 20],
    ],
  },
  {
    id: 'newsletter',
    triggers: ['newsletter', 'newsletters', 'digest', 'roundup', 'subscribed'],
    terms: [
      ['newsletter', 32],
      ['this week', 20],
      ['digest', 26],
      ['unsubscribe', 16],
      ['weekly roundup', 28],
      ['latest issue', 24],
    ],
  },
]

/** Words stripped from queries — they carry no search signal. */
export const STOPWORDS = new Set([
  'a', 'about', 'all', 'am', 'an', 'and', 'any', 'anything', 'are', 'as', 'at',
  'be', 'been', 'but', 'by', 'can', 'could', 'did', 'do', 'does', 'find', 'for',
  'from', 'get', 'give', 'got', 'had', 'has', 'have', 'he', 'her', 'him', 'his',
  'i', 'if', 'in', 'into', 'is', 'it', 'its', 'just', 'know', 'like', 'look',
  'looking', 'ma', 'may', 'me', 'might', 'mine', 'my', 'need', 'of', 'on', 'or',
  'out', 'please', 'search', 'see', 'she', 'should', 'show', 'so', 'some',
  'something', 'that', 'the', 'their', 'them', 'there', 'these', 'they', 'this',
  'those', 'to', 'up', 'us', 'want', 'was', 'we', 'were', 'what', 'when',
  'where', 'which', 'who', 'will', 'with', 'would', 'you', 'your',
])

/** Phrases that mean "I probably never opened it" → boost unread mail. */
export const MISSED_HINTS = [
  'missed',
  'miss',
  'unread',
  'never opened',
  "didn't see",
  'did not see',
  "haven't read",
  'have not read',
  'overlooked',
  'forgot',
  'forgotten',
]

/** Relative time windows mapped to Gmail's `newer_than` syntax. */
export const TIME_WINDOWS = [
  { match: ['today'], gmail: '1d', days: 1 },
  { match: ['yesterday'], gmail: '2d', days: 2 },
  { match: ['this week', 'past week', 'last week'], gmail: '7d', days: 7 },
  { match: ['two weeks', 'last two weeks', 'fortnight'], gmail: '14d', days: 14 },
  { match: ['this month', 'past month', 'last month'], gmail: '31d', days: 31 },
  { match: ['three months', 'last quarter', 'past quarter'], gmail: '90d', days: 90 },
  { match: ['six months', 'half year'], gmail: '180d', days: 180 },
  { match: ['this year', 'past year', 'last year'], gmail: '1y', days: 365 },
]
